spring:
  application:
    name: bangbang
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/bangbang
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bangbang
    username: bangbang
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
