spring:
  application:
    name: bangbang
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/bangbang
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bangbang
    username: bangbang
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

springdoc:
  packages-to-scan: com.bangbang
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
